version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build: ./infra/docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./src:/work

  web:
    build: ./infra/docker/nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./src:/work

  db:
    build: ./infra/docker/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
